FROM debian:stretch

ENV APP_HOME /app
ENV CONDA_HOME /etc/miniconda
ENV CONDA_VENV sentiment

RUN apt -y update \
 && apt -y install gnupg build-essential curl wget zip unzip vim apt-transport-https \
 && apt clean \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p ${APP_HOME}

WORKDIR ${APP_HOME}

RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && sh Miniconda3-latest-Linux-x86_64.sh -b -p ${CONDA_HOME} \
 && rm -rf Miniconda3-latest-Linux-x86_64.sh \
 && ln -sf ${CONDA_HOME}/bin/conda /usr/bin/conda \
 && echo ". ${CONDA_HOME}/etc/profile.d/conda.sh" >> ~/.bashrc

RUN ${CONDA_HOME}/bin/conda update -n base -c defaults conda

RUN conda create -y --name ${CONDA_VENV} python=3.7

ADD requirements_linux.txt requirements.txt

RUN bash -c "source ${CONDA_HOME}/bin/activate ${CONDA_VENV} \
 && pip install -r requirements.txt \
 && rm -rf requirements.txt"


ADD notebooks ./notebooks
ADD application.py .
ADD entrypoint.sh .
ADD model ./model

RUN chmod +x *.sh

CMD ["/bin/bash", "entrypoint.sh"]
